### PR TITLE
[ML Projects] --  Added the ML Projects 

### PR DESCRIPTION
**Pull request by Blacksujit**
# Added the Machine Learning Projects for Beginners 

This projects will help the beginners to get started with their Machine learning Journey 

For More Such ML Content  you can follow these blogs 

https://hashnode.com/@BlackShadow1

### CODE REVIEW

**Review by d-coder111 — CHANGES_REQUESTED** [review]
Hey @Blacksujit, following are suggested changes:
1)Could you add your projects inside "Data-Doodles" folder and don't create separate folder "ML Projects".
2)Delete the folder named destination folder.
3)Also delete credit card folder as that project has been already added by some one.
update it or fork it new and then raise a pr, I will merge that✌....kindly star the repo to show your support⭐.

**Comment by Blacksujit** [comment]
Ok I will change it

**Review by Blacksujit — COMMENTED** [review]
i have changed the folder directory as stated added the projects to the data doodles section

**Comment by Blacksujit** [comment]
can you check it and review once , i have added the projects to the data doodles directory and if there is anything suggest me the chnages i will change it

**Review by d-coder111 — APPROVED** [review]
We’re happy to have you with us. 💖We welcome and appreciate as many contributions as you can make!🚀✌
Don't forget to give it a star⭐....keep coding..keep learning! ✨😊

**Pull request merged**
